// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqRt6kh_LTZDSKgsrLVdZVnrCDgF3XdAg',
    appId: '1:682172366755:web:8f7d3eb453e78bdb8d6416',
    messagingSenderId: '682172366755',
    projectId: 'moxy-144f2',
    authDomain: 'moxy-144f2.firebaseapp.com',
    storageBucket: 'moxy-144f2.appspot.com',
    measurementId: 'G-SRWY3LZ3YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBay-38KCCx2S5rwsCwXf3Sj-Bs2QKb2uU',
    appId: '1:682172366755:android:038960b102f26b138d6416',
    messagingSenderId: '682172366755',
    projectId: 'moxy-144f2',
    storageBucket: 'moxy-144f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCncoSorcbmAdR2nWa_AnewJegfA9zvbM8',
    appId: '1:682172366755:ios:becc29a1c951a0a18d6416',
    messagingSenderId: '682172366755',
    projectId: 'moxy-144f2',
    storageBucket: 'moxy-144f2.appspot.com',
    iosClientId: '682172366755-8pnv5gd4543qlhcihjf8o7momjnteq1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.moxy',
  );
}
